<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Employees</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #333;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 40px;
                font-weight: 200;
                margin-bottom: 0;
            }

            table{
                display:inline-block;
                margin:0 auto;
                margin-top:30px;
                color:#222;
            }
            table tr th{
                color:#000;
                font-size:14px;
                background:#f2f2f2;
                padding:2px 10px;
            }
            table tr td{
                color:#222;
                text-align:left;
                font-size:12px;
                padding:2px 4px;
            }
            caption{
                line-height:40px;
            }
            a{
                color: #399;
                text-decoration:none;
            }
        </style>
    </head>
    <body>
        <h1>Employees</h1>
        <div>Prototipo de aplicación web</div>
        
        <table>
            <caption>
                <form method="POST">
                    <input type="text" name="q" value="<?= $q ?>"/>
                    <input type="submit" value="Buscar"/>
                </form>
            </caption>
            <tr>
                <th>NAME</th>
                <th>EMAIL</th>
                <th>POSITION</th>
                <th>SALARY</th>
                <th>ACTION</th>
            </tr>
            <?php foreach($employees as $employee): ?>
            <tr>
                <td><?= $employee['name'] ?></td>
                <td><?= $employee['email'] ?></td>
                <td><?= $employee['position'] ?></td>
                <td><?= $employee['salary'] ?></td>
                <td>[ <a href="/employees/<?= $employee['id'] ?>">Ver detalle</a> ]</td>
            </tr>
            <?php endforeach; ?>
        </table>
        <div>
            <form action="/employees.xml" method="GET" target="_new">
                <input type="number" name="min" value="0"/>
                <input type="number" name="max" value="0"/>
                <input type="submit" value="Liberar en XML"/>
            </form>
        </div>
    </body>
</html>


