<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Employees</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #333;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 40px;
                font-weight: 200;
                margin-bottom: 0;
            }

            table{
                display:inline-block;
                margin:0 auto;
                margin-top:30px;
                color:#222;
            }
            table tr th{
                color:#000;
                font-size:14px;
                background:#f2f2f2;
                padding:2px 10px;
            }
            table tr td{
                color:#222;
                text-align:left;
                font-size:12px;
                padding:2px 4px;
            }
            caption{
                line-height:40px;
            }
            caption a{
                color: #399;
                text-decoration:none;
                font-size:12px;
            }
        </style>
    </head>
    <body>
        <h1>Employees</h1>
        <div>Prototipo de aplicación web</div>
        
        <table>
            <caption>
                [ <a href="/employees">Regresar al listado</a> ]
            </caption>
            <tr>
                <th>NAME</th>
                <td><?= $employee['name'] ?></td>
            </tr>
            <tr>
                <th>EMAIL</th>
                <td><?= $employee['email'] ?></td>
            </tr>
            <tr>
                <th>PHONE</th>
                <td><?= $employee['phone'] ?></td>
            </tr>
            <tr>
                <th>ADDRESS</th>
                <td><?= $employee['address'] ?></td>
            </tr>
            <tr>
                <th>POSITION</th>
                <td><?= $employee['position'] ?></td>
            </tr>
            <tr>
                <th>SALARY</th>
                <td><?= $employee['salary'] ?></td>
            </tr>
            <tr>
                <th>SKILLS</th>
                <td> 
                    <ul>
                        <?php foreach($employee['skills'] as $skill): ?>
                        <li><?= $skill['skill'] ?></li>
                        <?php endforeach; ?>
                    </ul> 
                </td>
            </tr>
        </table>
    </body>
</html>


